### ISSUE TITLE
Add ability to pass options (timeout, etc) to Guzzle Client

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/guzzle6-adapter#2]

**Comment by sagikazarmark** [comment]
`send` accepts options

**Comment by sagikazarmark** [comment]
php-http/adapter#31

**Comment by sagikazarmark** [comment]
Is this still valid?

**Comment by dbu** [comment]
i guess this makes no sense. and the adapter should not instantiate the guzzle client but accept it as constructor argument, so the options can be done on the guzzle client directly.

**Comment by sagikazarmark** [comment]
The constructor accepts a client, but if none is passed, one is created. This allows zero configuration.
