### ISSUE TITLE
Revise Promise wrapper

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/guzzle6-adapter#23]

**Comment by sagikazarmark** [comment]
I think this is already done. Promise LGTM

@joelwurtz any possible issues you see? We had some with the exceptions, but those are solved I think.

**Comment by joelwurtz** [comment]
Currently no, but not so familiar with guzzle, anyway if there is a problem it will be bug but not a BC so no blocker for me

**Comment by sagikazarmark** [comment]
Ok, closing this then.
