### ISSUE TITLE
http://php-http.org domain is down.

### ISSUE THREAD

**Issue by perrupa** [php-http/guzzle6-adapter#4]
Thought this might be a good place to mention it.

You could always switch over to [Github pages](https://pages.github.com/)?

**Comment by hannesvdvreken** [comment]
It was never "up"

**Comment by hannesvdvreken** [comment]
;-)

**Comment by egeloen** [comment]
This is my fault. I will configure the DNS this week-end.

**Comment by sagikazarmark** [comment]
@egeloen can you add me as an admin contact to the domain. I know you bought it on Gandi, my Gandi Handle should work. Details in private.

**Comment by perrupa** [comment]
I'll pretend I never saw it ;)

**Comment by sagikazarmark** [comment]
The new website for the project is at http://httplug.io. As soon as @egeloen sets up the orga domain, we can set up a website there as well.

**Comment by dbu** [comment]
i would suggest to redirect to use just one domain.

**Comment by sagikazarmark** [comment]
No, PHP HTTP is still an organization open for other projects. If one day we start something else, it could also have it's own website.

My plan is to have an organization as a collection of HTTP related stuff, no matter what size. In that case, a somewhat general homepage for the organization might be useful.

**Comment by dbu** [comment]
okay.
