### ISSUE TITLE
Exception is thrown with 4XX and 5XX responses

### ISSUE THREAD

**Issue by tuupola** [php-http/guzzle6-adapter#41]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | v1.1.1

#### Actual Behavior

Documentation says:

> By default clients will always return a PSR-7 response instead of throwing a HttpException. Write your application to check the response status or use the Error Plugin to make sure the HttpException is thrown.

However both `sendRequest()` and `sendAsyncRequest()` throw an `HttpException` instead of returning the response. See example script below for comparing behaviour of different clients and `404`response.

https://gist.github.com/tuupola/527823d9a37848a6b35621204ec7b121

#### Expected Behavior

Call to `sendRequest()` should return response object with `404` status.  Promise from `sendAsyncRequest()` call should resolve to fulfilled promise and receive response object with `404` status.

#### Steps to Reproduce

```php
use Http\Adapter\Guzzle6\Client as Guzzle;
use GuzzleHttp\Client as GuzzleClient;
use Http\Message\MessageFactory\DiactorosMessageFactory;
use Http\Message\StreamFactory\DiactorosStreamFactory;
use Psr\Http\Message\ResponseInterface;

$nosuch = (new DiactorosMessageFactory)->createRequest("GET", "http://google.com/nosuch");
$guzzle = new Guzzle(new GuzzleClient);

$promise = $guzzle
    ->sendAsyncRequest($nosuch)
    ->then(function (ResponseInterface $response) {
        print "Guzzle async status: ". $response->getStatusCode() . "\n";
        return $response;
    });

try {
    $promise->wait();
    print "Guzzle promise state: " . $promise->getState() . "\n";
} catch (\Exception $exception) {
    print "Guzzle async exception: " . get_class($exception) . "\n";
}

try {
    $response = $guzzle->sendRequest($nosuch);
    print "Guzzle sync status: " . $response->getStatusCode() . "\n";
} catch (\Exception $exception) {
    print "Guzzle sync exception: " . get_class($exception) . "\n";
}

/*
$ php guzzle.php
Guzzle async exception: Http\Client\Exception\HttpException
Guzzle sync exception: Http\Client\Exception\HttpException
*/
```

**Comment by tuupola** [comment]
Above code works as expected when  Guzzle exceptions are disabled by setting `http_errors` to `false`. I guess this should used as default.

```php
$guzzle = Guzzle::createWithConfig(["http_errors" => false]);
```

**Comment by Nyholm** [comment]
When you providing the client yourself we assume you have configured it as you want.. That is why we do not modify the settings... 

```php
// Replace: 
$guzzle = new Guzzle(new GuzzleClient);

// With: 
$guzzle = new Guzzle();
```
