### ISSUE TITLE
Request for 1.2.0 stable

### ISSUE THREAD

**Issue by tractorcow** [php-http/guzzle6-adapter#44]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | master

Is there an ETA for stabilisation of the 1.2 minor version? I have a project that is currently relying on the unstable 1.2.x-dev branch, but I would love to use a stable tag.

**Comment by Nyholm** [comment]
What do you need?
The current release has no less features than master. https://github.com/php-http/guzzle6-adapter/compare/v1.1.1...master

**Comment by tractorcow** [comment]
I stand corrected, it looks like I jumped the gun with this request. Thanks for the prompt response!
