### ISSUE TITLE
Imposible to post via adapter

### ISSUE THREAD

**Issue by webmake** [php-http/guzzle6-adapter#45]
| Q            | A
| ------------ | ---
| Version      | 1.1.1

#### Actual Behavior
Post is absolutely useless via package, because not sending any options, so is it expected behaviour?

#### Steps to Reproduce
first server has such code:
```
var_export($_POST);die;
```
on second server such code:
```
    $config = [
        'connect_timeout' => 10,
        'timeout' => 10,
    ];
    $guzzle = new \GuzzleHttp\Client($config);
    $adapter = new \Http\Adapter\Guzzle6\Client($guzzle);

    $d["data1"] = rand(1, 1000);
    $d["data2"] =  rand(1, 1000);

    $request = new \GuzzleHttp\Psr7\Request('POST', 'http://testing.dev', ['form_params' => $d]);
    $response = $adapter->sendRequest($request);
    var_dump($response->getBody()->getContents());
```
output:
```
array (
)
```

#### Possible Solutions
Taking from original class, [\guzzlehttp\guzzle\src\Client.php:92](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L92)
`public function sendAsync(RequestInterface $request, array $options = [])` there is an option parameter, which catches any additional info, including form_data. But your code
```
    public function sendAsyncRequest(RequestInterface $request)
    {
        $promise = $this->client->sendAsync($request);

        return new Promise($promise, $request);
    }
```
does not pass such info. Neither in `sendRequest` [method](https://github.com/php-http/guzzle6-adapter/blob/master/src/Client.php#L54)

**Comment by Nyholm** [comment]
Hey. Sorry for not answering this issue in a while. 

There is nothing wrong with the adapter. It is just your server that does not reply with any content. Check the statusCode or some headers and you will see data.

**Comment by holtkamp** [comment]
I also encountered this "issue" caused by a difference in behavior. 

Maybe it was closed to soon, also see this discussion: https://stackoverflow.com/questions/34577278/guzzle-not-sending-psr-7-post-body-correctly
