### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/guzzle6-adapter#57]
Before releasing 2.0, I think we should release 1.2 as the last version in the 1.x release branch.

**Comment by Nyholm** [comment]
Generally I would agree with you, but not in this scenario. Looking at the [diff](https://github.com/php-http/guzzle6-adapter/compare/v1.1.1...master) you will see that there is a lot of changes but nearly non to `src/*`. We only add `final` to some classes which is breaking BC.

**Comment by sagikazarmark** [comment]
Yeah, I guess you are right: https://github.com/php-http/guzzle6-adapter/pull/55/files/6b48d74f125dc71be43219834208cc598f0ad912..58ec85113cff597cbb7cfcd79eab9be415120026#r229705833
