### ISSUE TITLE
Unable to install via Composer

### ISSUE THREAD

**Issue by Swader** [php-http/guzzle6-adapter#6]
Defining the `php-http/client-implementation` virtual package dependency interactively does not work, as it is unable to resolve a package.

Setting up both values manually in `composer.json` like so:

```
"require": {
        ...
        "php-http/client-implementation": "^1.0"
    },
    "require-dev": {
        ...
        "php-http/guzzle6-adapter": "^1.0"
    },
```

also fails with the following errors:

```
  Problem 1
    - The requested package php-http/client-implementation could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package php-http/guzzle6-adapter could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

@dbu says it's due to the adapter being outdated and providing the wrong thing.

FYI I am using php-http to replace the concrete Guzzle 5 dependency in [this lib](https://github.com/Swader/diffbot-php-client). The whole thing will result in a post on SitePoint.

**Comment by Swader** [comment]
On further inspection, the adapter as set in Packagist does indeed provide `adapter-implementation`. If someone could just push the most recent version to Packagist, that would solve things on that end, but it still doesn't clarify the error that says `php-http/guzzle6-adapter` can't be found in any version.

**Comment by dbu** [comment]
@sagikazarmark can you please add bruno on slack? i have no slack on my mobile to do it and out of home today.

**Comment by sagikazarmark** [comment]
Sure. @Swader can I use your sitepoint email address for slack.

As for the dependency problem: guzzle6-adapter currently has a 0.2 branch alias for dev-master. You could use `~0.2@dev` as a version constraint. The correct virtual package is `php-http/client-implementation`.

**Comment by Swader** [comment]
@sagikazarmark yeah, sure. bruno.skvorc@sitepoint.com will do fine, cheers

**Comment by sagikazarmark** [comment]
Invite sent

**Comment by sagikazarmark** [comment]
@Swader is this working for you now?

**Comment by Swader** [comment]
Have not checked yet, swarmed with other stuff atm, sorry. Will dive into it tomorrow.

**Comment by dbu** [comment]
great. note that you will need to have minimum-stability at dev for now to
get anything installed

**Comment by Swader** [comment]
Installed fine, proceeding with implementation
