### ISSUE TITLE
Composer Installation Failed

### ISSUE THREAD

**Issue by gustavobretas** [php-http/guzzle6-adapter#67]
| Q            | A
| ------------ | ---
| New Feature? | no
| Version      |  v2.0.0 

#### Actual Behavior
Composer is giving me a error return then the package isn't intalled.
![composer-fail](https://user-images.githubusercontent.com/5000754/50243252-b818f100-039a-11e9-82e2-a29785accb8e.jpg)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - Conclusion: don't install php-http/httplug v2.0.0
    - Installation request for php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1].

Installation failed, reverting ./composer.json to its original content.

#### Steps to Reproduce

Just exec the command: composer require php-http/guzzle6-adapter

Could someone help me with this issue, please?

**Comment by gustavobretas** [comment]
Hello @sagikazarmark , I got a answer from Mailgun, they advised me to run the following command.

> There was a recent update to the guzzle module required for our PHP SDK. You would need to specify the guzzle version when installing the Mailgun module. 

`php composer.phar require mailgun/mailgun-php php-http/guzzle6-adapter:~1.1.1 php-http/message`

Then it worked! =)

**Comment by sagikazarmark** [comment]
@gustavobretas I guess it's possible that mailgun doesn't work with httplug 2 yet, but I would still love to investigate the issue, so I would kindly ask you to provide the above requested information so we can fix the situation if there is a bug. Thank you!

**Comment by gustavobretas** [comment]
Hi @sagikazarmark, sure, my PHP Version is 7.2.4.

`    "require": {
        "php": ">=7.1.3",
        "anhskohbo/no-captcha": "3.*",
        "anlutro/l4-settings": "^0.4.6",
        "doctrine/dbal": "^2.8",
        "fideloper/proxy": "~4.0",
        "guzzlehttp/guzzle": "^6.3",
        "intervention/image": "^2.3",
        "jenssegers/agent": "^2.5",
        "laracasts/presenter": "^0.2.1",
        "laravel/framework": "5.6.*",
        "laravel/socialite": "^3.0",
        "laravelcollective/html": "^5.1",
        "league/fractal": "^0.16.0",
        "mailgun/mailgun-php": "^2.6",
        "paragonie/random_compat": "~1.4",
        "php-http/guzzle6-adapter": "~1.1.1",
        "php-http/message": "^1.7",
        "proengsoft/laravel-jsvalidation": "2.2.*",
        "tymon/jwt-auth": "1.0.0-rc.2",
        "webpatser/laravel-countries": "dev-master"
    },
    "require-dev": {
        "symfony/css-selector": "~4.0",
        "symfony/dom-crawler": "~4.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~7.0",
        "barryvdh/laravel-ide-helper": "2.4.*",
        "barryvdh/laravel-debugbar": "3.1.*",
        "laravel/browser-kit-testing": "^4.0",
        "filp/whoops": "~2.0"
    },`

I was trying to send the e-mails by Mailgun's sdk, but then I realized that Laravel already had it implemented! I'm using the Laravel class now and it is working fine! =)

Thank you!

**Comment by codeparl** [comment]
In my case, this is what i did:
I just added this line  `"guzzlehttp/guzzle": "^6.3",` in my composer.json
and issued the `composer update` command. Things worked well!

**Comment by kenkelvinmbaz** [comment]
i just change the line  that was before "guzzlehttp/guzzle": "^7.2" to "guzzlehttp/guzzle": "^6.3" and everything worked
