### ISSUE TITLE
Guzzle 7 support

### ISSUE THREAD

**Issue by jaikdean** [php-http/guzzle6-adapter#73]
**Description**

Guzzle 7 is now released. The differences between 6 and 7 are minimal, and having updated a few private libraries/projects it's generally trivial to support both.

**Comment by sagikazarmark** [comment]
Guzzle 7 is PSR-18 compatible, so you don't need an adapter for it. You can use it with HTTPlug 2 as is.

**Comment by gmponos** [comment]
There is this PR https://github.com/php-http/guzzle6-adapter/pull/72

**Comment by dbu** [comment]
yep, lets use the discussion in #72
