### ISSUE TITLE
production.ERROR: Interface 'Http\Client\HttpClient' not found

### ISSUE THREAD

**Issue by ashestree87** [php-http/guzzle6-adapter#74]
PHP 7.4

Receiving this error in the laravel log

[2020-07-06 09:20:11] production.ERROR: Interface 'Http\Client\HttpClient' not found {"exception":"[object] (Error(code: 0): Interface 'Http\\Client\\HttpClient' not found at /home/livefreshr/public_html/livefreshr.com/releases/113/vendor/php-http/guzzle6-adapter/src/Client.php:21)
[stacktrace]

Any idea how to resolve?

**Comment by xabbuh** [comment]
What is the output of `composer show` in this environment?

**Comment by ashestree87** [comment]
barryvdh/laravel-dompdf                       v0.8.6   A DOMPDF Wrapper for Laravel
barryvdh/laravel-snappy                       v0.4.7   Snappy PDF/Image for Laravel
beganovich/omnipay-checkout                   1.2.0    Checkout driver for the Omnipay PHP payment processing library
bjeavons/zxcvbn-php                           0.3.0    Realistic password strength estimation PHP library based on Zxcvbn JS
brick/math                                    0.8.15   Arbitrary-precision arithmetic library
brick/money                                   0.4.5    Money and currency library
cakephp/chronos                               2.0.5    A simple API extension for DateTime.
checkout/checkout-php-api                     1.2.18   Checkout PHP API Library
checkout/checkout-sdk-php                     1.0.8    Checkout.com SDK for PHP
chris-ware/nova-breadcrumbs                   1.3.6    A Laravel Nova tool.
chris-ware/nova-clock-card                    1.2.0    A Laravel Nova card to display the date and time.
clue/stream-filter                            v1.4.1   A simple and modern approach to stream filtering in PHP
davidpiesse/nova-map                          0.0.5    Map field for Laravel Nova
defuse/php-encryption                         v2.2.1   Secure PHP Encryption Library
digital-creative/collapsible-resource-manager v1.2.3   A custom sidebar menu with collapsible groups
dnoegel/php-xdg-base-dir                      v0.1.1   implementation of xdg base directory specification for php
doctrine/cache                                1.10.1   PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and o...
doctrine/dbal                                 2.10.2   Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/event-manager                        1.1.0    The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                            2.0.3    PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of w...
doctrine/lexer                                1.2.1    PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
dompdf/dompdf                                 v0.8.5   DOMPDF is a CSS 2.1 compliant HTML to PDF converter
dragonmantank/cron-expression                 v2.3.0   CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
ebess/advanced-nova-media-library             3.1.0    Laravel Nova tools for managing the Spatie media library.
egulias/email-validator                       2.1.17   A library for validating emails against several RFCs
eminiarts/nova-tabs                           1.2.2    Laravel Nova - Tabs.
fideloper/proxy                               4.3.0    Set trusted proxies for Laravel
firebase/php-jwt                              v5.2.0   A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
geo-io/interface                              v1.0.1   Geo I/O base interfaces.
geo-io/wkb-parser                             v1.0.1   Well-known binary (WKB) Parser.
giggsey/libphonenumber-for-php                8.12.5   PHP Port of Google's libphonenumber
giggsey/locale                                1.8      Locale functions required by libphonenumber-for-php
google/apiclient                              v2.5.0   Client library for Google APIs
google/apiclient-services                     v0.138   Client library for Google APIs
google/auth                                   v1.9.0   Google Auth Library for PHP
gregoriohc/laravel-nova-theme-responsive      v0.8.1   A Laravel Nova responsive theme.
grimzy/laravel-mysql-spatial                  2.2.3    MySQL spatial data types extension for Laravel.
guzzlehttp/guzzle                             6.5.4    Guzzle is a PHP HTTP client library
guzzlehttp/promises                           v1.3.1   Guzzle promises library
guzzlehttp/psr7                               1.6.1    PSR-7 message implementation that also provides common utility methods
inspheric/nova-email-field                    v1.42    A Laravel Nova email field.
intervention/image                            2.5.1    Image handling and manipulation library with support for Laravel integration
jjclane/laravel-sqlite-migrations             0.1.4    A trait to translate Laravel migrations into SQLite safe migrations.
jmikola/geojson                               1.0.2    GeoJSON implementation for PHP
knplabs/knp-snappy                            v1.2.1   PHP5 library allowing thumbnail, snapshot or PDF generation from a url or a html page. Wrapper for wkhtmltopdf/wkhtmltoimage.
kristories/nova-qrcode-field                  v0.0.1   Nova QR code field
laminas/laminas-diactoros                     2.3.0    PSR HTTP Message implementations
laminas/laminas-zendframework-bridge          1.0.4    Alias legacy ZF class names to Laminas Project equivalents.
laravel/framework                             v7.14.1  The Laravel Framework.
laravel/nova                                  v3.6.0   A wonderful administration interface for Laravel.
laravel/passport                              v8.5.0   Laravel Passport provides OAuth2 server support to Laravel.
laravel/tinker                                v2.4.0   Powerful REPL for the Laravel framework.
laravel/ui                                    v2.0.3   Laravel UI utilities and presets.
laravelcollective/html                        v6.1.2   HTML and Form Builders for the Laravel Framework
lcobucci/jwt                                  3.3.2    A simple library to work with JSON Web Token and JSON Web Signature
league/commonmark                             1.4.3    Highly-extensible PHP Markdown parser which fully supports the CommonMark spec and Github-Flavored Markdown (GFM)
league/event                                  2.2.0    Event package
league/flysystem                              1.0.69   Filesystem abstraction: Many filesystems, one API.
league/flysystem-cached-adapter               1.0.9    An adapter decorator to enable meta-data caching.
league/glide                                  1.5.0    Wonderfully easy on-demand image manipulation library with an HTTP based API.
league/iso3166                                2.1.5    ISO 3166-1 PHP Library
league/oauth2-server                          8.1.0    A lightweight and powerful OAuth 2.0 authorization and resource server library with support for all the core specification grants. This libra...
maatwebsite/excel                             3.1.19   Supercharged Excel exports and imports in Laravel
maatwebsite/laravel-nova-excel                1.2.1    Supercharged Excel exports for Laravel Nova Resources
maennchen/zipstream-php                       2.1.0    ZipStream is a library for dynamically streaming dynamic zip files from PHP without writing to the disk at all on the server.
markbaker/complex                             1.4.8    PHP Class for working with complex numbers
markbaker/matrix                              1.2.0    PHP Class for working with matrices
moneyphp/money                                v3.3.1   PHP implementation of Fowler's Money pattern
monolog/monolog                               2.1.0    Sends your logs to files, sockets, inboxes, databases and various web services
moontoast/math                                1.2.1    A mathematics library, providing functionality for large numbers
myclabs/php-enum                              1.7.6    PHP Enum implementation
nesbot/carbon                                 2.35.0   An API extension for DateTime that supports 281 different languages.
nikic/php-parser                              v4.5.0   A PHP parser written in PHP
nothingworks/blade-svg                        v0.3.4
nyholm/psr7                                   1.3.0    A fast PHP7 implementation of PSR-7
omnipay/common                                v3.0.4   Common components for Omnipay payment processing library
opis/closure                                  3.5.4    A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
optimistdigital/nova-sortable                 1.4.7    This Laravel Nova package allows you to reorder models in a Nova resource's index view using drag & drop.
paragonie/random_compat                       v9.99.99 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
pdewit/nova-external-url                      1.0.3    An external URL Laravel Nova field.
phenx/php-font-lib                            0.5.2    A library to read, parse, export and make subsets of different types of font files.
phenx/php-svg-lib                             v0.3.3   A library to read, parse and export to PDF SVG files.
philperusse/nova-column-filter                v0.3.0   A Laravel Nova column queryer filter
php-http/discovery                            1.7.4    Finds installed HTTPlug implementations and PSR-7 message factories
php-http/guzzle6-adapter                      v2.0.1   Guzzle 6 HTTP Adapter
php-http/httplug                              2.1.0    HTTPlug, the HTTP client abstraction for PHP
php-http/message                              1.8.0    HTTP Message related tools
php-http/message-factory                      v1.0.2   Factory interfaces for PSR-7 HTTP Message
php-http/promise                              v1.0.0   Promise used for asynchronous HTTP requests
phpoffice/phpspreadsheet                      1.13.0   PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpoption/phpoption                           1.7.4    Option Type for PHP
phpseclib/bcmath_compat                       1.0.5    PHP 5.x/7.x polyfill for bcmath extension
phpseclib/phpseclib                           2.0.27   PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
propaganistas/laravel-phone                   4.2.3    Adds phone number functionality to Laravel and Lumen based on Google's libphonenumber API.
psr/cache                                     1.0.1    Common interface for caching libraries
psr/container                                 1.0.0    Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                          1.0.0    Standard interfaces for event handling.
psr/http-client                               1.0.0    Common interface for HTTP clients
psr/http-factory                              1.0.1    Common interfaces for PSR-7 HTTP message factories
psr/http-message                              1.0.1    Common interface for HTTP messages
psr/log                                       1.1.3    Common interface for logging libraries
psr/simple-cache                              1.0.1    Common interfaces for simple caching
psy/psysh                                     v0.10.4  An interactive shell for modern PHP.
ralouphie/getallheaders                       3.0.3    A polyfill for getallheaders.
ramsey/collection                             1.0.1    A PHP 7.2+ library for representing and manipulating collections.
ramsey/uuid                                   4.0.1    A PHP library for generating and working with universally unique identifiers (UUIDs).
reedware/nova-text-filter                     v1.0.1   Adds a text filter component for resources and lenses.
s-ichikawa/laravel-sendgrid-driver            3.0.1    This library adds a 'sendgrid' mail driver to Laravel.
sabberworm/php-css-parser                     8.3.1    Parser for CSS Files written in PHP
sendgrid/php-http-client                      3.10.6   HTTP REST client, simplified for PHP
sendgrid/sendgrid                             7.5.2    This library allows you to quickly and easily send emails through Twilio SendGrid using PHP.
spatie/eloquent-sortable                      3.8.0    Sortable behaviour for eloquent models
spatie/image                                  1.7.6    Manipulate images with an expressive API
spatie/image-optimizer                        1.2.1    Easily optimize images using PHP
spatie/laravel-analytics                      3.9.0    A Laravel package to retrieve Google Analytics data.
spatie/laravel-medialibrary                   8.2.7    Associate files with Eloquent models
spatie/laravel-tags                           2.6.2    Add tags and taggable behaviour to your Laravel app
spatie/laravel-translatable                   4.3.2    A trait to make an Eloquent model hold translations
spatie/nova-tags-field                        3.0.0    A tags field for Nova apps
spatie/once                                   2.2.0    A magic memoization function
spatie/temporary-directory                    1.2.2    Easily create, use and destroy temporary directories
swiftmailer/swiftmailer                       v6.2.3   Swiftmailer, free feature-rich PHP mailer
symfony/cache                                 v5.1.0   Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts                       v2.1.2   Generic abstractions related to caching
symfony/console                               v5.1.0   Symfony Console Component
symfony/css-selector                          v3.1.10  Symfony CssSelector Component
symfony/deprecation-contracts                 v2.1.2   A generic function and convention to trigger deprecation notices
symfony/error-handler                         v5.1.0   Symfony ErrorHandler Component
symfony/event-dispatcher                      v5.1.0   Symfony EventDispatcher Component
symfony/event-dispatcher-contracts            v2.1.2   Generic abstractions related to dispatching event
symfony/finder                                v5.1.0   Symfony Finder Component
symfony/http-foundation                       v5.1.0   Symfony HttpFoundation Component
symfony/http-kernel                           v5.1.0   Symfony HttpKernel Component
symfony/intl                                  v5.1.0   A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mime                                  v5.1.0   A library to manipulate MIME messages
symfony/polyfill-ctype                        v1.17.0  Symfony polyfill for ctype functions
symfony/polyfill-iconv                        v1.17.0  Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme                v1.17.0  Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu                     v1.17.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn                     v1.17.0  Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer              v1.17.0  Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                     v1.17.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php72                        v1.17.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                        v1.17.0  Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                        v1.17.0  Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                               v5.1.0   Symfony Process Component
symfony/psr-http-message-bridge               v2.0.0   PSR HTTP message bridge
symfony/routing                               v5.1.0   Symfony Routing Component
symfony/service-contracts                     v2.1.2   Generic abstractions related to writing services
symfony/string                                v5.1.0   Symfony String component
symfony/translation                           v5.1.0   Symfony Translation Component
symfony/translation-contracts                 v2.1.2   Generic abstractions related to translation
symfony/var-dumper                            v5.1.0   Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                          v5.1.0   A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
tightenco/nova-google-analytics               v0.1.7   Google Analytics integration with Nova
tightenco/ziggy                               0.9.4    Generates a Blade directive exporting all of your named Laravel routes. Also provides a nice route() helper function in JavaScript.
tijsverkoyen/css-to-inline-styles             2.2.2    CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful when ...
titasgailius/search-relations                 1.0.5    A Laravel Nova tool.
vlucas/phpdotenv                              v4.1.7   Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
voku/portable-ascii                           1.5.1    Portable ASCII library - performance optimized (ascii) string functions for php.

**Comment by xabbuh** [comment]
Does the file `/home/livefreshr/public_html/livefreshr.com/releases/113/vendor/php-http/httplug/src/Client.php` exist?

**Comment by ashestree87** [comment]
yes its there?

**Comment by ashestree87** [comment]
<?php

namespace Http\Client;

use Psr\Http\Client\ClientInterface;

/**
 * {@inheritdoc}
 *
 * Provide the Httplug HttpClient interface for BC.
 * You should typehint Psr\Http\Client\ClientInterface in new code
 */
interface HttpClient extends ClientInterface
{
}

**Comment by ashestree87** [comment]
<?php

namespace Http\Client;

use Psr\Http\Client\ClientInterface;

/**
 * {@inheritdoc}
 *
 * Provide the Httplug HttpClient interface for BC.
 * You should typehint Psr\Http\Client\ClientInterface in new code
 */
interface HttpClient extends ClientInterface
{
}

**Comment by ashestree87** [comment]
`<?php

namespace Http\Client;

use Psr\Http\Client\ClientInterface;

/**
 * {@inheritdoc}
 *
 * Provide the Httplug HttpClient interface for BC.
 * You should typehint Psr\Http\Client\ClientInterface in new code
 */
interface HttpClient extends ClientInterface
{
}`

**Comment by xabbuh** [comment]
I don't know then. Maybe something goes wrong during the deployment and you need to dump the autoloader again (`composer dump-autoload` with appropriate options).

**Comment by ashestree87** [comment]
Seems to be working now. Think it was something to do with the config not getting cached.
