### ISSUE TITLE
Updating for PHP 8.0

### ISSUE THREAD

**Issue by bobstrecansky** [php-http/guzzle6-adapter#77]
**Description**

While using the guzzle6-adapter in [opentelemetry-php](https://github.com/open-telemetry/opentelemetry-php) I noticed that PHP 8.0 is not yet supported.  I think the version constraint [here](https://github.com/php-http/guzzle6-adapter/blob/master/composer.json#L18) might need to be changed to `>=7.1`, but there might be some additional testing necessary.

**Example**

You should be able to see this dependency resolution in this github action installation attempt:
https://github.com/bobstrecansky/opentelemetry-php/pull/6/checks?check_run_id=1364216037#step:6:14

**Comment by dbu** [comment]
are you sure that guzzle version 6 actually works on php 8? 
i'd recommend to use guzzle 7 which implements psr-18 natively, or if you need the php-http async interface, use guzzle 7 with guzzle7-adapter

**Comment by bobstrecansky** [comment]
I'll give that a go and report back. thanks @dbu !
