### ISSUE TITLE
Support for PHP8

### ISSUE THREAD

**Issue by tmp-hallenser** [php-http/guzzle6-adapter#80]
PHP8 has just been released. According to composer.json, this repo requires `"php": "^7.1"`. Any plans to make it work with PHP8?

**Comment by dbu** [comment]
guzzle 6 does not work with php 8, so this would not help (they used the `>7.1` version constraint, but that was a mistake). 

for php 8, you should use guzzle 7 (which implements psr-18 natively) or if you need the httplug async interface, use guzzle7-adapter with guzzle 7.
