### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by stof** [php-http/guzzle6-adapter#82]
**Description**

It would be great if this adapter could support PHP 8. Guzzle 6 allows it in composer.json

**Comment by xabbuh** [comment]
There was an earlier attempt in #76.

**Comment by stof** [comment]
I'm closing this as guzzle7-adapter supports PHP 8 and after investigation, the only package forcing me to use guzzle 6 rather than guzzle 7 in my project was this guzzle6-adapter.

**Comment by dbu** [comment]
also, guzzle 6 has a bad composer.json with `>= xy` instead of defining its tested range. and it actually does not work on php 8 afaik.

**Comment by GrahamCampbell** [comment]
👎 for allowing this. People and ignore the PHP req or upgrade.

**Comment by dbu** [comment]
see #83 and #86 for further discussion

**Comment by GrahamCampbell** [comment]
I still disagree with adding PHP 8 here.
