### ISSUE TITLE
Can not update some packages, because this package requires guzzlehttp/guzzle ^6.0 and not ^7.0

### ISSUE THREAD

**Issue by dennispansegrau** [php-http/guzzle6-adapter#89]
**Description**
Due to some conflics with guzzlehttp/guzzle version I cannot update other packages like google/cloud.
php-http/guzzle6-adapter v2.0.2 requires guzzlehttp/guzzle ^6.0

**Possible Solution**
Please add guzzlehttp/guzzle ^7.0 to the composer dependencies.

**Comment by dennispansegrau** [comment]
sorry I am stupid ;) there is a php-http/guzzle7-adapter :)

**Comment by dbu** [comment]
can confirm the second. not the first, you noticed yourself how to solve the problem :+1:
